### ISSUE TITLE
Undo messes with relative coordinates/bounds

### ISSUE THREAD

**Issue by CarlClasson** [microgui/MicroGUI#10]
When you delete a component and then press the 'Undo' button, the component renders in the correct place which is good! However, the bounds gets messed up, they are no longer relative to the upper-left corner of the canvas, but instead relative to the upper-left corner of the component itself.

**Comment by CarlClasson** [comment]
Very likely to be related to: #9

**Comment by wilhus** [comment]
Fixed in commit d12f713
