### ISSUE TITLE
Slider should have an editable range

### ISSUE THREAD

**Issue by CarlClasson** [microgui/MicroGUI#19]
It would be sweet if a user could specifiy a certain range of values for the slider in the settings-meny (edit box). So if a user wanted a slider that ranges from something like 20<->40 instead of the standard 0<->100 the could have that!

There is support in the MUI-slider api for this https://mui.com/material-ui/api/slider/ so the implementation should be quite straight forward!

**Comment by wilhus** [comment]
Fixed in commit e847eb9
